import type { ExportFormat } from "@/types/landing";

// Generate AI Plugin JSON for LLM discoverability
export function generateAIPluginJSON(title: string, description: string): string {
  const plugin = {
    schema_version: "v1",
    name_for_human: title,
    name_for_model: title.toLowerCase().replace(/\s+/g, "_"),
    description_for_human: description || `${title} - Professional landing page`,
    description_for_model: `This is the official website for ${title}. ${description || 'A professional landing page with information about products, services, or portfolio.'}`,
    auth: { type: "none" },
    api: { type: "none" },
    logo_url: "{{SITE_URL}}/logo.png",
    contact_email: "contact@example.com",
    legal_info_url: "{{SITE_URL}}/legal",
  };
  return JSON.stringify(plugin, null, 2);
}

export function convertToReact(html: string, title: string): string {
  const safeName = title.replace(/[^a-zA-Z0-9]/g, "");
  return `import React, { useEffect, useRef } from 'react';
import anime from 'animejs';

export default function ${safeName || "LandingPage"}() {
  const containerRef = useRef(null);

  useEffect(() => {
    // Initialize animations
    anime({
      targets: containerRef.current?.querySelectorAll('.animate-on-load'),
      opacity: [0, 1],
      translateY: [20, 0],
      delay: anime.stagger(100),
      duration: 800,
      easing: 'easeOutCubic',
    });
  }, []);

  return (
    <div ref={containerRef} dangerouslySetInnerHTML={{ __html: \`${html.replace(/`/g, "\\`").replace(/\$/g, "\\$")}\` }} />
  );
}
`;
}

export function convertToNextJS(html: string, title: string): string {
  const safeName = title.replace(/[^a-zA-Z0-9]/g, "");
  return `// app/page.tsx — Next.js App Router
'use client';

import { useEffect, useRef } from 'react';
import Script from 'next/script';

export const metadata = {
  title: '${title}',
  description: 'Generated by LandingCraft AI',
};

export default function ${safeName || "LandingPage"}() {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Anime.js animations init after hydration
    if (typeof window !== 'undefined' && (window as any).anime) {
      (window as any).anime({
        targets: containerRef.current?.querySelectorAll('[data-animate]'),
        opacity: [0, 1],
        translateY: [20, 0],
        delay: (window as any).anime.stagger(100),
        duration: 800,
        easing: 'easeOutCubic',
      });
    }
  }, []);

  return (
    <>
      <Script src="https://cdn.tailwindcss.com" strategy="beforeInteractive" />
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.2/anime.min.js" strategy="afterInteractive" />
      <div ref={containerRef} dangerouslySetInnerHTML={{ __html: \`${html.replace(/`/g, "\\`").replace(/\$/g, "\\$")}\` }} />
    </>
  );
}
`;
}

export function convertToTailwindProject(html: string, title: string): string {
  return `/*
 * Tailwind CSS Project Structure
 * Generated by LandingCraft AI
 *
 * To use this in a Tailwind project:
 *
 * 1. npx create-vite ${title.toLowerCase().replace(/\s+/g, "-")} --template vanilla-ts
 * 2. cd ${title.toLowerCase().replace(/\s+/g, "-")}
 * 3. npm install -D tailwindcss postcss autoprefixer
 * 4. npx tailwindcss init -p
 * 5. npm install animejs
 * 6. Replace index.html with the content below
 * 7. npm run dev
 *
 * tailwind.config.js content:
 * {
 *   "extend": { "fontFamily": { "sans": ["Inter", "sans-serif"] } }
 * }
 */

// ===== index.html =====
${html}
`;
}

export function exportAs(format: ExportFormat, html: string, title: string, description?: string): { content: string; filename: string; mime: string } {
  switch (format) {
    case "react":
      return { content: convertToReact(html, title), filename: `${slug(title)}.tsx`, mime: "text/typescript" };
    case "nextjs":
      return { content: convertToNextJS(html, title), filename: `page.tsx`, mime: "text/typescript" };
    case "tailwind":
      return { content: convertToTailwindProject(html, title), filename: `${slug(title)}-tailwind.txt`, mime: "text/plain" };
    case "ai-plugin":
      return { content: generateAIPluginJSON(title, description || ""), filename: `ai-plugin.json`, mime: "application/json" };
    default:
      return { content: html, filename: `${slug(title)}-landing.html`, mime: "text/html" };
  }
}

function slug(s: string) {
  return s.replace(/\s+/g, "-").toLowerCase();
}
